### ISSUE TITLE
Error: context.html.replace is not a function

### ISSUE THREAD

**Issue by borisovg** [alexnewmannn/metalsmith-inline-source#2]
```
TypeError: context.html.replace is not a function
    at parse (/home/borisov/test/metalsmith/node_modules/inline-source/lib/parse.js:17:27)
    at inlineSourceSync (/home/borisov/test/metalsmith/node_modules/inline-source/index.js:70:3)
    at /home/borisov/test/metalsmith/node_modules/metalsmith-inline-source/index.js:15:30
    at /home/borisov/test/metalsmith/node_modules/lodash/lodash.js:4738:15
    at baseForOwn (/home/borisov/test/metalsmith/node_modules/lodash/lodash.js:2879:24)
    at /home/borisov/test/metalsmith/node_modules/lodash/lodash.js:4707:18
    at Function.forEach (/home/borisov/test/metalsmith/node_modules/lodash/lodash.js:9011:14)
    at Ware.<anonymous> (/home/borisov/test/metalsmith/node_modules/metalsmith-inline-source/index.js:14:8)
    at Ware.<anonymous> (/home/borisov/test/metalsmith/node_modules/wrap-fn/index.js:45:19)
    at Immediate.next (/home/borisov/test/metalsmith/node_modules/ware/lib/index.js:85:20)
```

**Comment by alexnewmannn** [comment]
@borisovg Hey, didnt see this - never seen this notification! ill take a look at your PR now
